- hosts: localhost
  become: true

  tasks:

    - set_fact:
        KASA_HOSTNAME: "{{ lookup('file', '/etc/hostname') }}"

    - set_fact:
        SIEC: "{{ KASA_HOSTNAME.split('-')[0] }}"
  
    - name: Dodanie klucza do apta
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
  
    - name: Inslacja apt-transport-https
      apt:
        state: present
        name: apt-transport-https
        update_cache: no
  
    - name: Dodanie do repo
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic-8.x.list
  
    - name: Instalacja wtyczek
      apt:
        state: present
        update_cache: yes
        name:      
          - metricbeat
          - filebeat
  
    - name: Kopiowanie konfiguracji metricbeat
      template:
        src: templates/metricbeat.j2
        dest: /etc/metricbeat/metricbeat.yml
        vars:
          ELASTIC_HOST: "{{ ELASTIC_HOST_VAULT }}"
          ELASTIC_LOGIN: "{{ ELASTIC_LOGIN_VAULT }}"
          ELASTIC_PASS: "{{ ELASTIC_PASS_VAULT }}"
          KIBANA_HOST: "{{ KIBANA_HOST_VAULT }}"
          LOGSTASH_HOST: "{{ LOGSTASH_HOST_VAULT }}"
  
    - name: Kopiowanie konfiguracji filebeat
      template:
        src: templates/filebeat.j2
        dest: /etc/metricbeat/filebeat.yml
    
    - name: Wlaczanie uslug
      systemd:
         state: started
         enabled: yes
         name: "{{ item }}"
      loop:
        - metricbeat.service
        - filebeat.service

