- hosts: localhost
  become: true

  vars_files:
    - vault

  tasks:

    - set_fact:
        KASA_HOSTNAME_OLD: "{{ ansible_hostname }}"

    - name: Sprawdzam numer kasy
      command: grep numer_kasy /home/kasa/konfiguracja/zmienne.dat
      register: nr_kasy

    - name: Sprawdzam numer sklepu
      command: mysql kasa -Ns -e "select stan from StanKasy2 where idStanu='Numer Sklepu';"
      register: nr

    - set_fact:
        KASA_HOSTNAME: "{{ SIEC }}-s{{ nr.stdout }}-k{{ nr_kasy.stdout.split()[1] }}"

    - name: Ustawiam HOSTNAME
      debug:
        msg: "{{ KASA_HOSTNAME }}"

    - lineinfile:
        dest: /etc/hostname
        regexp: '.*'
        state: absent

    - name: Zmiana hostname
      lineinfile:
        dest: /etc/hostname
        line: '{{ KASA_HOSTNAME }}'

    - name: Zmiana w /etc/hosts
      replace:
        dest: /etc/hosts
        regexp: '(^127.*)(kasa.*)'
        replace: '\1{{ KASA_HOSTNAME }}'
        backup: yes

    - name: Dodanie klucza do apta
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Inslacja apt-transport-https
      apt:
        state: present
        name: apt-transport-https
        update_cache: yes

    - name: Dodanie do repo
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic-8.x.list

    - name: Instalacja wtyczek
      apt:
        state: present
        update_cache: yes
        name:
          - metricbeat
          - filebeat

    - name: Wylaczanie uslug
      systemd:
         state: stopped
         enabled: yes
         name: "{{ item }}"
      loop:
        - metricbeat.service
        - filebeat.service

    - name: Kopiowanie konfiguracji metricbeat
      template:
        src: templates/metricbeat.j2
        dest: /etc/metricbeat/metricbeat.yml

    - name: Kopiowanie konfiguracji metricbeat.system
      template:
        src: templates/system.j2
        dest: /etc/metricbeat/modules.d/system.yml

    - name: Kopiowanie konfiguracji filebeat
      template:
        src: templates/filebeat.j2
        dest: /etc/filebeat/filebeat.yml

    - name: Restart kasy
      command: "shutdown -r 23:15"